version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sire
    volumes:
      - db_data:/var/lib/mysql
      - ./procedure.sql:/docker-entrypoint-initdb.d/procedure.sql
    ports:
      - "3406:3406"
    networks:
      - flask_network

  app:
    build: .
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - flask_network
    environment:
      DATABASE_HOST: db  # Nombre de host para la aplicación Docker
      
volumes:
  db_data:

networks:
  flask_network:
      
