version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sire
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3406:3406"
    networks:
      - network

  app:
    build: .
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - network
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: sire
      
volumes:
  db_data:

networks:
  network:
    driver: bridge
      
